compress_html:
  clippings: all

locale: "en-US"
name: "Abolfazl Moslemian"
subtitle: "Personal Development Website"
title: Abolfazl Moslemian
masthead_title: "Abowfzl"
logo: "/assets/images/logo.webp"
title_separator: "-"
email: abowfzl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Abolfazl Moslemian, Principal Software Developer & Machine Learning & Data Science Specialist specializing in C#, Python, and cloud-based applications.

image: "/assets/images/default-preview.webp"
teaser: "/assets/images/default-preview.webp"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abowfzl.com"
permalink: pretty
twitter_username: abowfzl
github_username:  abowfzl

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
date_format: "%Y %B %d"
reading_time: true
enable_copy_code_button: true
google-site-verification: E4Fxn_g02ZE-UlvHa8LJMKLAR_YikeuFALXyiogMUdQ
google_fonts: true

search                   : true
search_full_content      :  true
lunr:
  search_within_pages    : true

comments:
  provider: "disqus"
  disqus:
    shortname:  abowfzl

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-gzip

author:
  name     : "Abofazl Moslemian"
  avatar   : "/assets/images/my-pic.jpg"
  bio      : "Life from the perspective of a programmer ;)"
  location : "Tehran, Iran"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abowfzl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abowfzl"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/abowfzl"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/17593676/abolfazl-moslemian"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:abowfzl@gmail.com"
    # - label: "Call Me"
    #   icon: "fa fa-fw fa-phone"
    #   url: "tel:+989129537270"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/abowfzl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abowfzl"
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/abowfzl"
      
assets:
  source_maps: true
  destination: "/assets"
  compression: true
  gzip: true
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  sources:
    - _assets/css
    - _assets/js
    - _assets/images


#blog settings
words_per_minute: 120
breadcrumbs:  true
copyright: Abolfazl Moslemian

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      show_date: true
      related: true
      image: /assets/images/default-preview.webp

      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true



# Reading Files
include:
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
